use uuid::Uuid;
use chrono::{Duration, Utc};
use crate::features::escrow::repository::EscrowRepository;
use crate::features::escrow::dto::*;
use crate::features::escrow::model::Escrow;
use crate::features::reputation::service::ReputationService;
use crate::features::notification::service::NotificationService;
use crate::shared::errors::AppError;
use crate::shared::utils::generate_deal_code;
use crate::shared::AppState;

pub struct EscrowService {
    repo: EscrowRepository,
    state: AppState,
}

impl EscrowService {
    pub fn new(repo: EscrowRepository, state: AppState) -> Self {
        Self { repo, state }
    }

    pub async fn create_escrow(
        &self,
        seller_id: Uuid,
        dto: CreateEscrowDto,
    ) -> Result<EscrowResponseDto, AppError> {
        // Generate unique escrow ID
        let escrow_id = format!("ESC-{}", uuid::Uuid::new_v4().to_string().split('-').next().unwrap().to_uppercase());
        
        // Generate 6-digit deal code
        let deal_code = generate_deal_code();
        
        // Convert amount to satoshis if needed (assuming amount is in smallest unit already)
        let amount_satoshis = dto.amount as i64;

        // Create escrow record
        let escrow = self.repo.create_escrow(
            &escrow_id,
            seller_id,
            amount_satoshis,
            &dto.currency,
            None, // deposit_address will be generated by canister
        ).await?;

        // Create deal code
        let expires_at = Utc::now() + Duration::hours(self.state.config.deal_code_expiry_hours);
        self.repo.create_deal_code(
            &deal_code,
            &escrow_id,
            seller_id,
            &dto.buyer_phone,
            Some(expires_at),
        ).await?;

        // Get seller's trust score
        let reputation_service = ReputationService::new(self.state.reputation_repo.clone());
        let trust_score = reputation_service.get_trust_score(seller_id).await.unwrap_or(50);
        let trust_badge = reputation_service.get_trust_badge(trust_score).await;

        // Send SMS to buyer
        let notification_service = NotificationService::new(self.state.clone());
        let message = format!(
            "You have a payment request for {}{}.\nTo fund, reply: FUND {}\nOr dial {} and select option 2",
            self.format_currency(dto.amount, &dto.currency),
            dto.currency,
            deal_code,
            self.state.config.africastalking_ussd_short_code
        );
        
        notification_service.send_sms(&dto.buyer_phone, &message).await?;

        Ok(EscrowResponseDto {
            escrow_id,
            deal_code,
            amount: dto.amount,
            currency: dto.currency,
            buyer_phone: dto.buyer_phone,
            status: "CREATED".to_string(),
            trust_score,
            trust_badge,
            created_at: escrow.created_at,
        })
    }

    pub async fn fund_escrow(
        &self,
        dto: FundEscrowDto,
    ) -> Result<EscrowStatusDto, AppError> {
        // Find deal code
        let deal = self.repo.find_by_deal_code(&dto.deal_code)
            .await?
            .ok_or_else(|| AppError::NotFound("Invalid deal code".to_string()))?;

        // Find escrow
        let mut escrow = self.repo.find_escrow_by_id(&deal.escrow_id)
            .await?
            .ok_or_else(|| AppError::NotFound("Escrow not found".to_string()))?;

        // Update status to FUNDED
        self.repo.update_escrow_status(&deal.escrow_id, "FUNDED").await?;
        escrow.status = "FUNDED".to_string();
        escrow.funded_at = Some(Utc::now());

        // Send notifications
        let notification_service = NotificationService::new(self.state.clone());
        let message = format!(
            "Deal funded. Funds secured in escrow.\nDeal Code: {}\nAmount: {}{}",
            dto.deal_code,
            escrow.amount_satoshis,
            escrow.currency
        );

        // Get seller phone
        let auth_repo = &self.state.auth_repo;
        if let Some(seller) = auth_repo.find_by_id(deal.seller_id).await? {
            if let Some(phone) = seller.phone_number {
                notification_service.send_sms(&phone, &message).await?;
            }
        }

        notification_service.send_sms(&deal.buyer_phone, &message).await?;

        Ok(EscrowStatusDto {
            escrow_id: escrow.escrow_id.clone(),
            deal_code: dto.deal_code,
            amount: escrow.amount_satoshis as u64,
            currency: escrow.currency.clone(),
            status: escrow.status,
            seller_phone: None,
            buyer_phone: Some(deal.buyer_phone),
            created_at: escrow.created_at,
            funded_at: escrow.funded_at,
            released_at: None,
        })
    }

    pub async fn release_escrow(
        &self,
        buyer_id: Uuid,
        dto: ReleaseEscrowDto,
    ) -> Result<EscrowStatusDto, AppError> {
        // Verify PIN
        let auth_service = crate::features::auth::service::AuthService::new(
            self.state.auth_repo.clone(),
            self.state.config.clone(),
        );
        
        if !auth_service.verify_pin(buyer_id, &dto.approval_pin).await? {
            return Err(AppError::Unauthorized("Invalid PIN".to_string()));
        }

        // Find deal code
        let deal = self.repo.find_by_deal_code(&dto.deal_code)
            .await?
            .ok_or_else(|| AppError::NotFound("Invalid deal code".to_string()))?;

        // Find escrow
        let mut escrow = self.repo.find_escrow_by_id(&deal.escrow_id)
            .await?
            .ok_or_else(|| AppError::NotFound("Escrow not found".to_string()))?;

        if escrow.status != "FUNDED" {
            return Err(AppError::BadRequest("Escrow is not funded".to_string()));
        }

        // Update status to RELEASED
        self.repo.update_escrow_status(&deal.escrow_id, "RELEASED").await?;
        escrow.status = "RELEASED".to_string();
        escrow.released_at = Some(Utc::now());

        // Mark deal code as used
        self.repo.mark_deal_code_used(&dto.deal_code).await?;

        // Update reputation
        let reputation_service = ReputationService::new(self.state.reputation_repo.clone());
        reputation_service.update_reputation(deal.seller_id, "deal_completed").await?;
        reputation_service.update_reputation(buyer_id, "deal_completed").await?;

        // Send notifications
        let notification_service = NotificationService::new(self.state.clone());
        let message = format!(
            "Payment released. Balance updated.\nDeal Code: {}\nAmount: {}{}",
            dto.deal_code,
            escrow.amount_satoshis,
            escrow.currency
        );

        // Get seller phone
        let auth_repo = &self.state.auth_repo;
        if let Some(seller) = auth_repo.find_by_id(deal.seller_id).await? {
            if let Some(phone) = seller.phone_number {
                notification_service.send_sms(&phone, &message).await?;
            }
        }

        Ok(EscrowStatusDto {
            escrow_id: escrow.escrow_id.clone(),
            deal_code: dto.deal_code,
            amount: escrow.amount_satoshis as u64,
            currency: escrow.currency.clone(),
            status: escrow.status,
            seller_phone: None,
            buyer_phone: Some(deal.buyer_phone),
            created_at: escrow.created_at,
            funded_at: escrow.funded_at,
            released_at: escrow.released_at,
        })
    }

    pub async fn get_escrow_status(
        &self,
        deal_code: &str,
    ) -> Result<EscrowStatusDto, AppError> {
        let deal = self.repo.find_by_deal_code(deal_code)
            .await?
            .ok_or_else(|| AppError::NotFound("Invalid deal code".to_string()))?;

        let escrow = self.repo.find_escrow_by_id(&deal.escrow_id)
            .await?
            .ok_or_else(|| AppError::NotFound("Escrow not found".to_string()))?;

        Ok(EscrowStatusDto {
            escrow_id: escrow.escrow_id.clone(),
            deal_code: deal.deal_code.clone(),
            amount: escrow.amount_satoshis as u64,
            currency: escrow.currency.clone(),
            status: escrow.status.clone(),
            seller_phone: None,
            buyer_phone: Some(deal.buyer_phone),
            created_at: escrow.created_at,
            funded_at: escrow.funded_at,
            released_at: escrow.released_at,
        })
    }

    fn format_currency(&self, amount: u64, currency: &str) -> String {
        match currency {
            "NGN" => format!("₦{:.2}", amount as f64 / 100.0),
            "USD" => format!("${:.2}", amount as f64 / 100.0),
            _ => format!("{} ", amount),
        }
    }
}

